# Programas de inicialização automática
exec_always --no-startup-id ~/.config/polybar/launch.sh
exec --no-startup-id volti
exec --no-startup-id nm-applet
exec --no-startup-id parcellite
exec --no-startup-id /usr/bin/numlockx on
exec --no-startup-id sh ~/.fehbg
exec --no-startup-id setxkbmap -model pc105 -layout us -variant intl
