# Cores de janelas
client.focused              #4e6072 #4e6072 #CCCCCC #ffcfaf
client.focused_inactive     #3f3f3f #3F3F3F #7f9f7f #3f3f3f
client.unfocused            #3f3f3f #3F3F3F #DCDCCC #3f3f3f
client.urgent               #dca3a3 #dca3a3 #DCDCCC #3f3f3f
