#!/opt/homebrew/bin/lua

-- Carrega os módulos se existirem
require "helpers"
require "init"

-- Define os atributos do item "media"
sketchybar("--add", "item", "media", "center")
sketchybar("--set", "media", "script=/Users/renan-dev/.config/sketchybar/helpers/media.sh", "updates=on")
sketchybar("--subscribe", "media", "media_change")
